name: CI

on:
  push:
    branches: [mainline]
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: leafo/gh-actions-lua@v10
        with:
          luaVersion: "5.1"
      - uses: leafo/gh-actions-luarocks@v6
      - run: luarocks install busted
      - run: busted spec/

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: JohnnyMorganz/stylua-action@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          version: 2.4.0
          args: --check lua/ spec/
      - uses: leafo/gh-actions-lua@v10
        with:
          luaVersion: "5.1"
      - uses: leafo/gh-actions-luarocks@v6
      - run: luarocks install luacheck
      - run: luacheck lua/ spec/

  selene:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@main
      - uses: DeterminateSystems/magic-nix-cache-action@main
      - run: nix develop -c selene --display-style=quiet lua/ spec/
